version: '3.5'

services:
  storybook:
    container_name: shesha-reactjs-storybook
    build:
      context: .
      dockerfile: development.dockerfile
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development